### ISSUE TITLE
Gekisou Sentai Carranger has terrible quality front-art

### ISSUE THREAD

**Issue by Anime0t4ku** [Anime0t4ku/TapToCassetteCovers#1]
Couldn't find any decent resolution assetts for the front cover. Hope it will "pop-up" some day.

**Comment by JaydeSix** [comment]
How about this
![Gekisou Sentai Carranger - Zenkai Racer Senshi](https://github.com/user-attachments/assets/59a21b47-f61c-4e12-9121-9f79245a7ef9)

**Comment by Anime0t4ku** [comment]
Awesome work!, will add it to the main branch once I get back home.
