### ISSUE TITLE
Incorrect summary on Goldeneye 007

### ISSUE THREAD

**Issue by BLuR-42** [Anime0t4ku/TapToCassetteCovers#17]
FYI the cassette cover for Goldeneye has the summary for Diddy Kong Racing on it.
[Goldeneye](https://github.com/Anime0t4ku/TapToCassetteCovers/blob/main/Games/Nintendo%20-%20N64%20(USA)/Goldeneye%20007.png)

**Comment by Anime0t4ku** [comment]
Fixed: https://github.com/Anime0t4ku/TapToCassetteCovers/blob/main/Games/Nintendo%20-%20N64%20(USA)/Goldeneye%20007_v2.png

**Comment by Anime0t4ku** [comment]
Updated version uploaded
